### ISSUE TITLE
感觉这个项目要凉

### ISSUE THREAD

**Issue by xywf221** [polarphp/polarphp#20]
如题 春哥已经三天莫得更新了,是在憋大招还是准备放弃了！

**Comment by zzusoftboy** [comment]
因为遇到瓶颈了呀 这几天一直再研究swift 相关代码 找灵感呢，libSytanx 怎么 跟 bison 和 re2c 结合，老铁，别慌

**Comment by wudi** [comment]
春哥只是最近套页面需求比较多，难以抽身
理解

**Comment by huanghantao** [comment]
加油！

**Comment by xywf221** [comment]
@zzusoftboy  加油！
