### ISSUE TITLE
有点疑惑

### ISSUE THREAD

**Issue by xywf221** [polarphp/polarphp#21]
看了下春哥最近的commit竟然把zendvm给删了 !不禁有点疑问 : 春哥以后对polarphp的定位是hack对PHP修修补补勉强使用，还是准备拿PHP的一些语法跟特性再造门全新的语言？ @zzusoftboy

**Comment by zzusoftboy** [comment]
polarphp 定位是 PHP 语言的另一种实现，包括完整的vm + 标准库

**Comment by zzusoftboy** [comment]
其实不用关闭的，可以让更多的人看到
