### ISSUE TITLE
怎么看php的新提案p++

### ISSUE THREAD

**Issue by xywf221** [polarphp/polarphp#24]
如题春哥怎么看待p++

**Comment by zzusoftboy** [comment]
太激进，可以无限接近强类型，但是红线不能过，过了就是新语言了，另外 P++ 好难听，还不如叫 typephp 呢

**Comment by xywf221** [comment]
> 太激进，可以无限接近强类型，但是红线不能过，过了就是新语言了，另外 P++ 好难听，还不如叫 typephp 呢

其实我感觉php最爽的一点就是简单，强行搞强类型，不如换个语言去玩。

**Comment by zzusoftboy** [comment]
你说的对

**Comment by xywf221** [comment]
在这里问下啊春哥，我是一直关注polarphp的进度，但是看你每次得提交都是Syntax的基本语法，没学过c++也贡献不了，本年年底能出个测试版本不？毕竟我从18年12月份就开始关注了。

**Comment by freedomgeeks** [comment]
已经被全票驳回
